version: 2.1

workflows:
  build_test:
    jobs:
      - node/test:
          matrix:
            parameters:
              version:
                - 14.0.0
                - 13.11.0
                - 12.16.0
      - push-image-ACR:
          requires:
            - node/test
      - hold:
          type: approval
          requires:
            - build_docker_image
      - slack-notification:
          requires:
            - build_docker_image


jobs:
  slack-notification:
    executor: node/default
    steps:
      - slack/notify:
          color: "#42e2f4"
          mentions: "nexpeque"
          message: Dev image built! :D
      - slack/status:
          fail_only: true
          mentions: "nexpeque"

  push-image-ACR:
    docker:
      - image: cimg/node:14.0.0
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: false
      - run: 
          name: Set up tag 
          command: echo "export TAG=0.1.$CIRCLE_SHA1" >> $BASH_ENV    
      - azure-acr/build-and-push-image:
          dockerfile: Dockerfile
          login-server-name: "$REGISTRY_NAME.azurecr.io"
          registry-name: "$REGISTRY_NAME"
          repo: "$REGISTRY_NAME.azurecr.io/$REGISTRY_NAME"
          tag: TAG


orbs:
  node: circleci/node@4.0.0
  slack: circleci/slack@3.4.2
  azure-acr: circleci/azure-acr@0.2.0